language: go
go:
  - 1.4.2
  - tip
before_install:
  - ./travis_install_capstone.sh
  - ./genconst $HOME/src/capstone-3.0.3/bindings/python/capstone
  - ./genspec $HOME/src/capstone-3.0.3/tests
notifications:
  email:
    recipients:
      - travis@ben.iagu.net
