language: go
go:
  - 1.4.3
  - 1.5.3
  - 1.6.1
  - 1.7.3
  - tip
sudo: false
before_install:
  - ./genconst capstone/bindings/python/capstone
  - ./genspec capstone/tests
notifications:
  email:
    recipients:
      - travis@ben.iagu.net
