language: go
go:
  - 1.4.2
sudo: false
before_install:
  - ./travis_install_capstone_next.sh
  - ./genconst $HOME/src/capstone/bindings/python/capstone
  - ./genspec $HOME/src/capstone/tests
  - export LIBRARY_PATH=$HOME/capstone/lib
  - export C_INCLUDE_PATH=$HOME/capstone/include
notifications:
  email:
    recipients:
      - travis@ben.iagu.net
