#!/usr/bin/env ruby

require 'open3'

# I hate these little scripts :(

unless ARGV.length == 1 && File.directory?(ARGV[0])
	$stderr.puts "Usage: #{$0} path/to/capstone/tests"
	exit
end
stub = ARGV[0].chomp('/')

commands = [
	"#{stub}/test.static > $GOPATH/src/github.com/bnagy/gapstone/test.SPEC",
	"#{stub}/test_detail.static > $GOPATH/src/github.com/bnagy/gapstone/test_detail.SPEC",
	"#{stub}/test_arm.static > $GOPATH/src/github.com/bnagy/gapstone/arm.SPEC",
	"#{stub}/test_arm64.static > $GOPATH/src/github.com/bnagy/gapstone/arm64.SPEC",
	"#{stub}/test_x86.static > $GOPATH/src/github.com/bnagy/gapstone/x86.SPEC",
	"#{stub}/test_mips.static > $GOPATH/src/github.com/bnagy/gapstone/mips.SPEC",
	"#{stub}/test_ppc.static > $GOPATH/src/github.com/bnagy/gapstone/ppc.SPEC",
	"#{stub}/test_systemz.static > $GOPATH/src/github.com/bnagy/gapstone/sysZ.SPEC",
	"#{stub}/test_sparc.static > $GOPATH/src/github.com/bnagy/gapstone/sparc.SPEC",
	"#{stub}/test_xcore.static > $GOPATH/src/github.com/bnagy/gapstone/xcore.SPEC"
]

commands.each {|c|
	_, err, status = Open3.capture3 c
	if not status.success?
		$stderr.puts "#{$0}: error running command: #{err}"
		exit
	end
	puts "Wrote: #{c.split.last}"
}
